export  const SPECIALITIES = [
    { specialities: "ALERGIA"} ,
    { specialities: "ALERGIA E INMUNOLOGIA"} ,
    { specialities: "CARDIOLOGIA" } ,
    { specialities: "CARDIOLOGIA INFANTIL"} ,
    { specialities: "CIRUGIA PLASTICA Y REPARADORA"} ,
    { specialities: "CIRUGIA TORACICA"} ,
    { specialities: "CIRUGIA GENERAL"} ,
    { specialities: "CIRUGIA CARDIOVASCULAR"} ,
    { specialities: "CIRUGIA INFANTIL"} ,
    { specialities: "CLINICA MEDICA: Medicina Interna"} ,
    { specialities: "DERMATOLOGIA"} ,
    { specialities: "DIAGNOSTICO POR IMAGENES"} ,
    { specialities: "ENDOCRINOLOGIA"} ,
    { specialities: "INFECTOLOGIA PEDIÁTRICA"} ,
    { specialities: "GASTROENTEROLOGIA"} ,
    { specialities: "GENETICA MEDICA"} ,
    { specialities: "GERIATRIA Y GERONTOLOGIA"} ,
    { specialities: "GINECOLOGIA"} ,
    { specialities: "MEDICINA LEGAL"} ,
    { specialities: "MEDICINA DEL TRABAJO"} ,
    { specialities: "MEDICINA GENERAL / FAMILIAR"} ,
    { specialities: "NEONATOLOGIA"} ,
    { specialities: "NEUMONOLOGIA"} ,
    { specialities: "NEUROCIRUGIA"} ,
    { specialities: "NEUROLOGIA"} ,
    { specialities: "NEUROLOGIA INFANTIL"} ,
    { specialities: "NUTRICION"} ,
    { specialities: "OBSTETRICIA"} ,
    { specialities: "OFTALMOLOGIA"} ,
    { specialities: "ONCOLOGIA (Clínica)"} ,
    { specialities: "OTORRINOLARINGOLOGIA"} ,
    { specialities: "PEDIATRIA (Clínica Pediátrica)"} ,
    { specialities: "PSIQUIATRIA"} ,
    { specialities: "PSIQUIATRIA INFANTO JUVENIL"} ,
    { specialities: "RADIOTERAPIA (Terapia Radiante)"} ,
    { specialities: "SALUD PUBLICA"} ,
    { specialities: "TERAPIA INTENSIVA"} ,
    { specialities: "TISIONEUMONOLOGIA"} ,
    { specialities: "TOCOGINECOLOGIA"} 
];
